config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get '/register', to: 'users#new', as: 'register'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: 'logout'
  get '/pin', to: 'sessions#pin', as: 'pin'
  post '/pin', to: 'sessions#pin'

  resources :posts, except: [:destroy] do
    member do
      post 'vote'
    end

    resources :comments, only: [:create] do
      member do
        post 'vote'
      end
    end
  end

  resources :categories, only: [:new, :create, :show]
  resources :users, only: [:show, :create, :edit, :update]
end

app/views/shared/_comment.html.erb
<% show_post ||= false %>

<div class="row">
  <div class="span0 well text-center">
    <%= link_to vote_post_comment_path(comment.post, comment, vote: true), method: 'post', remote: true do %>
      <i class="icon-arrow-up"></i>
    <% end %>
    <br/>
    <span id="comment_<%= comment.id %>_votes"><%= comment.overall_votes %></span>
    <br/>
    <%= link_to vote_post_comment_path(comment.post, comment, vote: false), method: 'post', remote: true do %>
      <i class="icon-arrow-down"></i>
    <% end %>
  </div>

  <div class="well span8">
    <em><%= comment.body %></em>
    <% if show_post %>
      on <%= link_to comment.post.title, post_path(comment.post) %>
    <% end %>
    <p>by <%= link_to comment.creator.username, user_path(comment.creator) %> at <%= format_datetime(comment.created_at) %></p>
  </div>
</div>

app/views/shared/_content_title.html.erb
<p class="lead">
  <%= title %>
  <hr/>
</p>

app/views/shared/_errors.html.erb
<% if active_record_object.errors.any? %>
  <div class="row">
    <div class="alert alert-error span8">
      <h5>Please fix the following errors:</h5>
      <ul>
        <% active_record_object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>