config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get '/register', to: 'users#new', as: 'register'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: 'logout'
  get '/pin', to: 'sessions#pin', as: 'pin'
  post '/pin', to: 'sessions#pin'

  resources :posts, except: [:destroy] do
    member do
      post 'vote'
    end

    resources :comments, only: [:create] do
      member do
        post 'vote'
      end
    end
  end

  resources :categories, only: [:new, :create, :show]
  resources :users, only: [:show, :create, :edit, :update]
end

app/models/post.rb
class Post < ActiveRecord::Base
  PER_PAGE = 5

  include Voteable
  include Sluggable

  default_scope { order('created_at DESC') }

  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  has_many :comments
  has_many :post_categories, foreign_key: :post_id
  has_many :categories, through: :post_categories

  validates :title, presence: true, length: {minimum: 5}
  validates :description, presence: true
  validates :url, presence: true, uniqueness: true

  sluggable_column :title
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :vote]
  before_action :require_user, except: [:index, :show]
  before_action :require_creator, only: [:edit, :update]

  def index
    @posts = Post.limit(Post::PER_PAGE).offset(params[:offset])
    @pages = Post.all.size / Post::PER_PAGE
    rollover = Post.all.size % Post::PER_PAGE != 0
    @pages += 1 if rollover
    # .sort_by{ |post| post.overall_votes }.reverse
  end

  def show
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.creator = current_user

    if @post.save
      flash['notice'] = "Your post was created."
      redirect_to posts_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash['notice'] = "This post was updated."
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def vote
    @vote = Vote.create(voteable: @post, creator: current_user, vote: params[:vote])

    respond_to do |format|
      format.html do
        if @vote.valid?
          flash['notice'] = 'Your vote was counted.'
        else
          flash['error'] = "You have already voted on this post"
        end
        redirect_to :back
      end
      format.js
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :url, :description, category_ids: [])
  end

  def set_post
    @post = Post.find_by(slug: params[:id])
  end

  def require_creator
    if (logged_in? && current_user != @post.creator && !current_user.admin?)
      access_denied
    end
  end
end

app/views/posts/_form.html.erb
<%= render 'shared/errors', active_record_object: @post %>

<div class="well">
  <%= form_for @post do |f| %>
    <div class="control-group">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <div class="control-group">
      <%= f.label :url %>
      <%= f.text_field :url %>
    </div>
    <div class="control-group">
      <%= f.label :description %>
      <%= f.text_area :description, rows: 5 %>
    </div>
    <div class="control-group">
      <%= f.label "Categories" %>
      <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |checkbox| %>
        <% checkbox.label(class: "checkbox inline") {checkbox.check_box(class: "checkbox") + checkbox.text} %>
      <% end %>
    </div>
    <%= f.submit(@post.new_record? ? 'Create Post' : 'Update Post' , class: 'btn btn-primary') %>
  <% end %>
</div>

app/views/posts/_post.html.erb
<div class="row">
  <div class="span0 well text-center">
    <%= link_to vote_post_path(post, vote: true), method: 'post', remote: true do %>
      <i class="icon-arrow-up"></i>
    <% end %>
    <br/>
    <span id="post_<%= post.slug %>_votes"><%= post.overall_votes %></span>
    <br/>
    <%= link_to vote_post_path(post, vote: false), method: 'post', remote: true do %>
      <i class="icon-arrow-down"></i>
    <% end %>
  </div>
  <div class="span8 well">
    <%= render post.categories %>
    <h4><%= link_to post.title, format_url(post.url) %></h4>
    <p><%= post.description %></p>
    <p>
      <span class='quiet'>posted by</span> <%= link_to post.creator.username, user_path(post.creator) %>
      <small>at <%= format_datetime(post.created_at) %></small>
    </p>
    <small>
      <span>
        <%= link_to("#{post.comments.length} comments", post_path(post)) %>
      </span>
    </small>
  </div>
</div>

app/views/posts/edit.html.erb
<%= render 'shared/content_title', title: 'Edit this post' %>
<%= render 'form' %>

app/views/posts/index.html.erb
<%= render 'shared/content_title', title: 'All Posts' %>

<% @posts.each do |post| %>
  <%= render 'post', post: post %>
<% end %>

<% @pages.times do |n| %>
  <% if params[:offset].to_s == (n * Post::PER_PAGE).to_s %>
    <%= "Page #{n + 1}" %> |
  <% else %>
    <%= link_to "Page #{n + 1}", posts_path(offset: n * Post::PER_PAGE) %> |
  <% end %>
<% end %>

app/views/posts/new.html.erb
<%= render 'shared/content_title', title: 'Create a new post' %>
<%= render 'form' %>

app/views/posts/show.html.erb
<% if logged_in? && @post.creator == current_user || current_user.admin? %>
  <p class="pull-right">
    [<%= link_to 'Edit this post', edit_post_path(@post) %>]
  </p>
<% end %>

<p>
  <%= render @post.categories %>
</p>

<%= render 'shared/content_title', title: @post.title %>

<p>
  <%= @post.description %>
</p>
<hr/>

<% if logged_in? %>
  <%= form_for [@post, @comment] do |f| %>
    <%= render 'shared/errors', active_record_object: @comment %>
    <div class="control-group">
      <%= f.label :body, 'Leave a comment' %>
      <%= f.text_area :body, rows: 3, class: 'span4' %>
    </div>
    <%= f.submit "Create comment", class: "btn btn-primary" %>
  <% end %>
<% end %>

<h4>Comments:</h4>
<% @post.reload.comments.reverse.each do |comment| %>
  <%= render 'shared/comment', comment: comment %>
<% end %>

app/views/posts/vote.js.erb
<% if @vote.valid? %>
  $('#post_<%= @post.slug %>_votes').html('<%= @post.overall_votes %>');
<% else %>
  alert('You have already voted on this')
<% end %>